// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Todo2.Infrastructure;

#nullable disable

namespace Todo2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Todo2.Domain.toDo", b =>
                {
                    b.Property<int>("taskNum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("taskNum"));

                    b.Property<bool>("done")
                        .HasColumnType("bit");

                    b.Property<string>("taskDue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("taskName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("taskNum");

                    b.ToTable("ToDos");

                    b.HasData(
                        new
                        {
                            taskNum = 1,
                            done = false,
                            taskDue = "3/8/2024",
                            taskName = "2022 Exam"
                        },
                        new
                        {
                            taskNum = 2,
                            done = false,
                            taskDue = "12/8/2024",
                            taskName = "Finish angular videos"
                        },
                        new
                        {
                            taskNum = 3,
                            done = false,
                            taskDue = "15/8/2024",
                            taskName = "Change gym workout routine"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
